### ISSUE TITLE
Print affiliated package version number in test output

### ISSUE THREAD

**Issue by cdeil** [astropy/package-template#104]
When getting bug reports from users it would very useful to have the affiliated package version number printed in the test log.

Currently this info is not printed:
https://gist.github.com/cdeil/32777e5beaba9278d85f
(the package location is printed, which does contain a folder name like `packagename-0.0.dev144-py2.7-macosx-10.9-x86_64.egg`, but that's a bit hidden and might not always contain the version number)

**Comment by astrofrog** [comment]
I think this was resolved by @bsipocz in https://github.com/astropy/package-template/commit/708b628fd98a058c423fbcd741aaab2a7d69530d so closing. Feel free to re-open if this does not address your issue.
