### ISSUE TITLE
Undocumented behavior that test framework resets ConfigItems to defaults can cause incorrect test failures.

### ISSUE THREAD

**Issue by mperrin** [astropy/package-template#106]
I'm reporting here some undocumented behavior of the test framework that just cost me a lot of time and confusion. I'm not sure if the right fix is better documentation or better behavior.  The underlying problem is that the test framework apparently resets configuration items to their default values, regardless of any other modifications to them that might take place in program code. The end result is that  under some circumstances correctly working code fails in the test framework.

In my package poppy, I had code along the lines of the following (highly simplified):

``` python
class Conf(_config.ConfigNamespace):
    use_optional_library = _config.ConfigItem(True, "should some optional library be used?")
conf=Conf()

try: 
    import package_required_only_for_optional_feature
except:
    conf.use_optional_library = False

def somefunction():

     if not conf.use_optional_library:
           do_a_thing()
     else:
          do_it_a_faster_way_using_that_package()

```

The intent is that the code should try the faster way by default, but fall back to the slow way if the fast one is not available - and furthermore that the user has the option to explicitly choose the slow method if desired (for instance the fast one doesn't yet play well with multiprocessing, etc.).  Because this is computationally intensive code, I don't want to try/except every time you call the function, it should try the import once and thereafter remember whether or not it's present. 

When ran interactively on a machine lacking the optional library, the above code works as designed: it detects that the import fails, turns off that setting, and just does the calculation the slower way. 

However, when ran via the test framework (either `import package; package.test()` or `python setup.py test`), then the test framework apparently resets all the Conf settings back to the default, thus undoing the effect of the try/except block. So the code tries to use the optional library, and fails. 

@cslocum tells me that @embray says this behavior is by design, but it's highly non-obvious and confusing to me.  This is the second time that undocumented features in the test system have derailed things for me (see https://github.com/astropy/astropy/issues/2502 for the other). Can I suggest/request that it would be worth the effort to document more carefully as part of the astropy package template guide what the underlying assumptions and automatic behaviors are?

**Comment by pllim** [comment]
See https://github.com/astropy/package-template#deprecation-warning
