### ISSUE TITLE
Affiliated package install re-installs Astropy core command line tools

### ISSUE THREAD

**Issue by cdeil** [astropy/package-template#111]
I just noticed that `python setup.py install --user` for `package-template` (and all other affiliated packages) re-installs the Astropy core command line tools:

``` bash
$ python setup.py install --user
...
creating /Users/deil/Library/Python/3.4/lib/python/site-packages/packagename-0.0.dev162-py3.4-macosx-10.10-x86_64.egg
Extracting packagename-0.0.dev162-py3.4-macosx-10.10-x86_64.egg to /Users/deil/Library/Python/3.4/lib/python/site-packages
packagename 0.0.dev162 is already the active version in easy-install.pth
Installing script_example script to /Users/deil/Library/Python/3.4/bin

Installed /Users/deil/Library/Python/3.4/lib/python/site-packages/packagename-0.0.dev162-py3.4-macosx-10.10-x86_64.egg
Processing dependencies for packagename==0.0.dev162
Searching for astropy==1.0.dev10599
Best match: astropy 1.0.dev10599
Processing astropy-1.0.dev10599-py3.4-macosx-10.10-x86_64.egg
astropy 1.0.dev10599 is already the active version in easy-install.pth
Installing fitscheck script to /Users/deil/Library/Python/3.4/bin
Installing fitsdiff script to /Users/deil/Library/Python/3.4/bin
Installing fitsheader script to /Users/deil/Library/Python/3.4/bin
Installing samp_hub script to /Users/deil/Library/Python/3.4/bin
Installing volint script to /Users/deil/Library/Python/3.4/bin
Installing wcslint script to /Users/deil/Library/Python/3.4/bin

Using /Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.0.dev10599-py3.4-macosx-10.10-x86_64.egg
...
```

I don't know from where it installed e.g. `fitscheck`, but the file modification time tells me that it really touched that file:

``` bash
$ ls -lh /Users/deil/Library/Python/3.4/bin/fitscheck 
-rwxr-xr-x  1 deil  staff   199B Dec 11 10:41 /Users/deil/Library/Python/3.4/bin/fitscheck
```

@embray @astrofrog I guess affiliated package install has no reason to touch Astropy command line tools and this is a bug?

**Comment by weaverba137** [comment]
I definitely don't want this behavior!  We need to have clear separation of scripts in our workflow, that is, we work in an environment where version control is very important (we use the Modules system to load versions), and we can't have extraneous scripts in one package hiding scripts in the package that we actually want.

**Comment by astrofrog** [comment]
@embray - as pointed out by @cdeil, this happens even without pip. Is this normal?

**Comment by cdeil** [comment]
I think this should be considered a bug, command line scripts installed by Python packages should be independent. I've never seen this with other Python packages. But @embray commented that this is normal behaviour!?

**Comment by astrofrog** [comment]
It does seem like it could be a setuptools thing, it's in the section of the install log after the code has been installed where it processes the dependencies:

```
Processing dependencies for wcsaxes==0.5.dev545
Searching for matplotlib==1.4.2
Best match: matplotlib 1.4.2
Adding matplotlib 1.4.2 to easy-install.pth file

Using /Users/tom/miniconda3/envs/production/lib/python3.4/site-packages
Searching for astropy==1.0.2
Best match: astropy 1.0.2
Adding astropy 1.0.2 to easy-install.pth file
Installing fits2bitmap script to /Users/tom/miniconda3/envs/production/bin
Installing fitsdiff script to /Users/tom/miniconda3/envs/production/bin
Installing fitscheck script to /Users/tom/miniconda3/envs/production/bin
Installing samp_hub script to /Users/tom/miniconda3/envs/production/bin
Installing wcslint script to /Users/tom/miniconda3/envs/production/bin
Installing volint script to /Users/tom/miniconda3/envs/production/bin
Installing fitsheader script to /Users/tom/miniconda3/envs/production/bin

Using /Users/tom/miniconda3/envs/production/lib/python3.4/site-packages
Searching for numpy==1.9.2
Best match: numpy 1.9.2
Adding numpy 1.9.2 to easy-install.pth file
```

Maybe you can report it to setuptools to see what they think?

**Comment by cdeil** [comment]
Given that there are thousands of Python package using setuptools it's more likely that this is an issue with `astropy-helpers` or `astropy`. I wouldn't know what to say exactly in a `setuptools` issue, so @astrofrog, if you think it's useful, could you please file it?

**Comment by astrofrog** [comment]
I'll try and find another example to see if there is the same behavior. What other packages have scripts?

**Comment by cdeil** [comment]
On my machine there's not many Python packages that install scripts (see [here](https://gist.github.com/cdeil/8cfe440a4f3c019f200c)).
E.g. IPython or Sphinx or tox.

**Comment by weaverba137** [comment]
For the record, I observed this while testing the pydl package, using `python setup.py install --prefix ...`.  So no `pip` involved, at least not directly.  This was on the head of the master branch, which I'm working on converting to the latest package-template tag.

**Comment by cdeil** [comment]
I'm also seeing this with `python setup.py`, without `pip`, so as @astrofrog said, the issue must be there.

**Comment by astrofrog** [comment]
And it's not astropy-specific. I took PyAVM (which doesn't use astropy-helpers and doesn't list astropy as a dependency) and set ``coveralls`` as a dependency and got:

```
Best match: coveralls 1.0a2
Processing coveralls-1.0a2-py3.4.egg
coveralls 1.0a2 is already the active version in easy-install.pth
Installing coveralls script to /Users/tom/miniconda3/envs/production/bin
```

This is setuptools, and is not related to Astropy.

**Comment by weaverba137** [comment]
I think I have a clue as to what's going on.  I was working on my Mac laptop, which has MacPorts installed.  MacPorts often renames command-line scripts, so on my machine the astropy script `fits2bitmap` becomes `fits2bitmap-ap-2.7`. So I think setuptools is installing scripts that it can't find because they have been renamed.

**Comment by cdeil** [comment]
So `setuptools` is lying when it prints this line?
```
Installing coveralls script to /Users/tom/miniconda3/envs/production/bin
```
If so, I agree, it's worth filing an issue there.

@astrofrog Can you paste the full log of the command(s) you ran (probably in a gist if it's long).

**Comment by astrofrog** [comment]
I'm not using MacPorts. I opened an issue with setuptools here to ask for clarification. To reproduce, take the pyavm package, add ``install_requires=['coveralls']`` then run ``python setup.py install``.

**Comment by embray** [comment]
At some point I'm going to look into what it would take to make `./setup.py install` default to basically doing the same thing pip does when installing a package (see for example https://bitbucket.org/pypa/setuptools/issue/371/setuptools-and-state-of-pep-376 for recent discussion related to this).

I don't know if this behavior is intentional or a bug (I lean toward slight bug), but in any case it's a legacy of setuptools using easy_install to install dependencies listed in `install_requires`, and it has very different (and in many cases unwanted) behavior.

To be honest, although for as long as distutils has been around the way to install Python packages was to run `setup.py install`, the eventual trend is going to be away from that.  The eventual goal is for distutils+setuptools to just be a build tool.  It will create a package (source or binary) that pip will handle the installation of.  I recommend if you want consistent behavior to not use `setup.py install` with packages, and instead run `pip install .`.  Then pip will handle the installation of the package and do the same thing it does when you use `pip install` to download a package from a package index.

**Comment by weaverba137** [comment]
Our group is still being periodically bitten by this bug.  Has anything turned up or changed with regards to this?

**Comment by pllim** [comment]
Any answers from the bitbucket links above? I clicked on them but then they asked me to create an account and then said my account info is wrong, then I gave up.

**Comment by bsipocz** [comment]
@pllim - I believe ``setuptools`` also moved to github, so no wonder the bitbucket links are not working any more.

**Comment by pllim** [comment]
Unfortunately, I don't think they transferred old issues over from bitbucket. I can't find issue titled "scripts are re-installed when packages are" 😞

**Comment by saimn** [comment]
https://github.com/pypa/setuptools/issues/371 (and with the same number :wink: )

**Comment by pllim** [comment]
pypa/setuptools#395 was closed as "won't fix", so... I am not sure if there is anything we can do about it.

**Comment by cdeil** [comment]
I re-read some of the old discussion above. @pllim - yes, I think this is just setuptools behaviour, so keeping this issue open isn't useful. Closing now.
