### ISSUE TITLE
github_issues_url should be set in conf.py

### ISSUE THREAD

**Issue by mwcraig** [astropy/package-template#117]
`astropy-helpers` expects this variable to be set if there is a changelog for which links to github issues are automatically being generated when the documentation is built. See https://github.com/astropy/astropy/blob/master/docs/conf.py#L187 for the locationof this line in astropy.

Will do a PR to fix later this week unless someone else gets to it first.

**Comment by astrofrog** [comment]
I wonder whether we should be using the github project variable from ``setup.cfg`` to avoid having to define the same thing twice?

**Comment by pllim** [comment]
Irrelevant due to #438

**Comment by astrofrog** [comment]
This is not so much irrelevant as already solved in prior PRs:

https://github.com/astropy/package-template/blob/999de51f7f1cef769491627c0ddbe94b02af45a4/%7B%7B%20cookiecutter.package_name%20%7D%7D/docs/conf.py#L170
