### ISSUE TITLE
Structure of docs directory

### ISSUE THREAD

**Issue by weaverba137** [astropy/package-template#118]
Why does the package-template suggest putting all real documentation inside the `docs/packagename` directory when astropy itself does not do this?  If this is documented somewhere, I guess I just couldn't find it.

**Comment by astrofrog** [comment]
So the original idea behind this was that in astropy, we do follow this structure for sub-packages, e.g. ``docs/table``. So the idea was that for affiliated packages that would be merged into the core, it would make it easier if the future sub-package docs were in the right place.

BUT I think that it's true that most affiliated packages are now not intended for merging in future, so I would be in favor of dropping this layout and the requirement for the sub-directory. Some packages have done that anyway:

http://photutils.readthedocs.org/en/latest/

**Comment by embray** [comment]
I guess maybe the docs could be changed to state this as a suggestion but not as a rule.

**Comment by weaverba137** [comment]
I will submit a PR shortly, but I just wanted to note that the [main astropy documentation for affiliated packages](http://astropy.readthedocs.org/en/latest/development/affiliated-packages.html), which is referenced in the README.rst file, appears to be agnostic on this topic.  So only the docs/index.rst file appears to still reference this rule.
