### ISSUE TITLE
license of packages using this template

### ISSUE THREAD

**Issue by hamogu** [astropy/package-template#149]
The files in this template are BSD licensed - that's what the license says and that's what the first line in most "*.py" files says.
Does that mean that we lock all users of the template to use the BSD licence, too? As a developer for an affiliated package I don't own the files I copied over form the package-template, so I don't have the right to change their license.

I suggest adding a sentence like "All files in this package are released under the following licenses: BSD, MIT, GPL, ... (users choice)"
I'm not a lawyer, but the employs very similar language "or, at the user's discretion, any later version".

(Note that this is a theoretical concern. I am certain that the astropy project is not going to sue an affiliated package developer for copyright infringement.)

**Comment by astrofrog** [comment]
@hamogu - no, as far as I understand you can take a BSD project and re-release it under a more restrictive license if you want. The BSD is not viral like the GPL. You can even use BSD code in commercial packages, so you could make a paid version of Astropy ;)

**Comment by astrofrog** [comment]
According to the license, the only requirement is that there is a mention somewhere of the original copyright of the code.

**Comment by hamogu** [comment]
I don't think that's quite true. From the license:

-    Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

where the following disclaimer is: 
THIS SOFTWARE [...] SUCH DAMAGE.

which means that I essentially have to reproduce the BSD license for those files that could be considered "redistributions", i.e. those where I did not change much.
That's not a real problem, nothing stops me of having different licenses for different files in my package. It's just annoying.
(Again, I acknowledge that this is more of a theoretical discussion. Also, many affiliated packages use the BSD license anyway.)

*Note* that the license file in this repro is currently broken: The first line says "Copyright (c) year, author All rights reserved." where year and author should be replaced with actual values.

**Comment by mwcraig** [comment]
Is there any reason not to make the package template public domain? Don't really have any feelings about this, to be honest, but that would be the least restrictive route.

**Comment by astrofrog** [comment]
@hamogu - you can keep the text of the license without actually saying *you* are licensing it under BSD. Here's an example of me re-using some BSD code:

https://github.com/astrofrog/vispy-multivol/blob/master/multivol/shaders.py

I chose to also license my modified version under BSD, but I could also have re-licensed it under e.g. GPL (while mentioning the text of the original license as the original license)

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
