### ISSUE TITLE
Update to numpy 1.10?

### ISSUE THREAD

**Issue by dkirkby** [astropy/package-template#152]
Are there plans to update the default version of numpy in .travis.yml to 1.10.x, and perhaps retire some older versions of numpy?

**Comment by bsipocz** [comment]
@dkirkby - I think deciding on which numpy versions are supported (and when versions are dropped) and tested against should be up to the individual packages and not to this tempate.
However #148 actually updates the versions in the template ``.travis.yml``.

 Alternatively one can set ``stable`` as numpy version in both ``.travis.yml`` and ``appveyor.yml`` which will be resolved to be the latest stable version (however if there isn't any tests against numpy dev, or the beta releases there may be some unexpected failures when switching to a new release).

**Comment by dkirkby** [comment]
@bsipocz - Thanks for the feedback.

I think people starting with this template will assume that it tests the same matrix as the astropy main package, in order to streamline the process of eventually incorporating new code via the affiliated package mechanism.  Since astropy is still using 1.9 as its default, it makes sense to mirror that here.

Feel free to close this issue.
