### ISSUE TITLE
New package-template release before pyastro16

### ISSUE THREAD

**Issue by bsipocz** [astropy/package-template#153]
The last release of the template was last May. I think it may be useful to make one before (or at?) pyastro16, so people wanting to use it for their packages start from a more up-to-date version.
There are quite a lot of open PRs that can go into the new version.

I'm willing to help if there is anything I can do in this process.

cc @astrofrog @eteq

**Comment by pllim** [comment]
Looks like this missed the pyastro16. But still :+1: on next release.

**Comment by bsipocz** [comment]
The new release is tagged, so closing.
