### ISSUE TITLE
Failure if data directory contains subdirectories

### ISSUE THREAD

**Issue by ehsteve** [astropy/package-template#155]
This is apparently related issue described on [Stackoverflow](http://stackoverflow.com/questions/3712033/python-distutils-error-directory-doesnt-exist-or-not-a-regular-file) and Issue [19286](https://bugs.python.org/issue19286) on the Python bug list. If I simply comment out the following line from setup.py

    package_info['package_data'][PACKAGENAME].append('data/*')

then all is well.

**Comment by pllim** [comment]
I remember encountering this a while ago as well.

But if you just comment out that line, does your package data still get installed? For my case, I remember replacing that line with a slightly different incantation instead of just commenting it out.

**Comment by pllim** [comment]
I attempted to address this in astropy/astropy#4744

**Comment by pllim** [comment]
I think the updated Astropy doc should address this. If not, feel free to re-open with suggestions.
