### ISSUE TITLE
Mocking with package-template

### ISSUE THREAD

**Issue by bmorris3** [astropy/package-template#160]
I'm trying to use the package template with a project of mine, [`shampoo`](https://github.com/bmorris3/shampoo).

The testing/CI stuff is working great, and now I'm trying to set up read the docs. Two dependencies in my package require C libraries to be installed (`pyfftw`, `h5py`), and there's no way to install C libraries on RTD. I've tried their [FAQ solution](http://read-the-docs.readthedocs.org/en/latest/faq.html) for mocking packages, and I've tried the snippet of code in #18 that @keflavich recommended be added to the package-template docs ([see here](https://github.com/astropy/package-template/issues/18#issuecomment-43441155)). Neither have worked. Does anyone have ideas on how to fool sphinx? 

Here's the [latest failed RTD build](https://readthedocs.org/projects/shampoo/builds/3870022/), here's my package's [failing `docs/conf.py` mock implementation](https://github.com/bmorris3/shampoo/blob/master/docs/conf.py#L163-L181).

cc @bsipocz @cdeil

**Comment by bmorris3** [comment]
I did just get the build to work – it's important to put the bit of code that @keflavich mentioned above the first line where the package gets imported in `docs/conf.py`, which looks like `__import__(setup_cfg['package_name'])`. 

I may do a quick PR to add a note about this do the package-template docs, if anyone thinks that's useful.

**Comment by astrofrog** [comment]
@bmorris3 - just so you know, it is possible to set up dependencies using conda now (we do it for astropy core). h5py would be easy to install, and I'm sure pyfftw is in a conda channel somewhere?

**Comment by bsipocz** [comment]
Closing as I think astropy/astropy#4754 addresses this. Please feel free to reopen if you think more docs is needed.
