### ISSUE TITLE
What to do with all these open PRs?

### ISSUE THREAD

**Issue by pllim** [astropy/package-template#161]
Can I just go ahead and merge the ones that make sense to me? What is the process here? I see a lack of activity.

**Comment by astrofrog** [comment]
I'm supposed to be a maintainer, so I can take a look at them on Wednesday. The last few weeks have been a bit crazy :laughing:

**Comment by astrofrog** [comment]
But it would be helpful if you can go through and review them too, and add a :+1: if you think they are good to go.

**Comment by pllim** [comment]
I guess your hands were Glued to something else. Okay, then. Thanks for following up!

**Comment by astrofrog** [comment]
LOL :smile:

**Comment by pllim** [comment]
You  mean a real comment with the hand emoji, or just a "reaction" (the new thingy GitHub just added)?

**Comment by pllim** [comment]
@astrofrog , okay, I went the "old school" route and added some comments to the PRs that I find desirable to be in the template. Thanks!
