### ISSUE TITLE
Testing affiliated packages that require scipy in Python 3.5

### ISSUE THREAD

**Issue by weaverba137** [astropy/package-template#165]
I'd like to be able to run Travis tests in Python 3.5, but currently there is a package compatibility issue in anaconda that prevents the installation of scipy, which my package requires.

Apologies if this issue is already being tracked elsewhere.

**Comment by astrofrog** [comment]
@weaverba137 - this should be reported in https://github.com/astropy/ci-helpers - could you open an issue there and also expand on the package incompatibility? (including any relevant logs). Thanks!

**Comment by weaverba137** [comment]
Issue has moved to astropy/ci-helpers#80.
