### ISSUE TITLE
Travis CI - Numpy versions

### ISSUE THREAD

**Issue by MSeifert04** [astropy/package-template#173]
I realized that ``conda`` doesn't have current astropy builds for older numpy versions. For example numpy 1.8/1.7 uses astropy 1.0.3, numpy 1.9 uses astropy 1.0.4.

Is there anything one could do except specifying astropy dev as requirement (which slows the tests down significatly) for the test?

**Comment by bsipocz** [comment]
I think this is not a package-template issue, but a more general ``ci-helpers`` one.

Yes, conda doesn't build packages for all combination of versions. 
There is ``astropy-ci-extras`` that hosted some of these unstandard combinations, but it hasn't been updated for a while.

All other options would need to build the package in the CI VM, thus take time. One option e.g. (I think it should work though I haven't tested it) don't specify ``ASTROPY_VERSION``, only ``NUMPY_VERSION``, and then list astropy with the required version in ``PIP_REQUIREMENTS``. However if you have any other package that requires astropy, don't conda install, but pip install it, too.

**Comment by MSeifert04** [comment]
Sorry I thought this would be a template issue since it's de facto affecting the packages built on this template.

@bsipocz Thank you for the suggestion. I'll give it a try with pip :+1:

**Comment by bsipocz** [comment]
On the other hand it's very unlikely that using conda anyone would install those combinations ;)

 ``astropy-ci-extras`` is in the conda channel list, so if ever there is a willing volunteer with enough free time on their hands to build these and upload there, they will get used by default.

Let me know whether it works out with pip.

**Comment by mwcraig** [comment]
I am happy to help get a build repo going for astropy-ci-extras....I just don't think I'll have time to keep up its maintenance.

Thanks,
Matt Craig

**Comment by MSeifert04** [comment]
@bsipocz Today conda with numpy 1.9 installed astropy 1.0.1 and I finally decided to test it. And it works if I use something like:

```
        - python: 2.7
          env: NUMPY_VERSION=1.9
               ASTROPY_VERSION=''
               PIP_DEPENDENCIES='astropy>=1.1'
```
It takes a bit longer (around 20-30 seconds) to build with pip and it's quite annoying that all packages depending on astropy need to be added to the pip dependencies.

@mwcraig An all conda solution would be amazing but not necessary given that pip works and ci time is probably "cheap" compared to your time. :smile:

**Comment by mwcraig** [comment]
For astropy itself you are probably right -- it doesn't take that long to build (especially on travis), so if we can avoid building it, great. There may be some python/numpy combinations for which building a numpy package would be handy.

**Comment by MSeifert04** [comment]
@mwcraig You mean like building numpy 1.11 for python 3.4 / 3.3?

Does it provide an real advantage? You'd need to build any package against this np111py34 combination as well because not many packages in the main conda/astropy channel are built against this combination.

**Comment by mwcraig** [comment]
@MSeifert04 Something like that. It is not clear to me what numpy/python combinations we actually intend to support. Astropy supports numpy 1.7 or higher, and python 3.3 or higher (I think), but I don't know if that is intended to imply that all possible combinations of those versions are supported. I tend to think that people using, e.g. python 3.3 have not updated their numpy (or are unable to do so), and that people running python 3.5 are probably not also using numpy 1.7.

**Comment by bsipocz** [comment]
@mwcraig - I think we can safely assume that py3.5 doesn't need old numpies. 

However it can be very well the case that someone is stuck with py3.3 but has up to date packages installed with ``--user``. E.g. I was one of these people for a long time (either on a server or on my old laptop where python came from fink but the support stopped for that old OS). Anyway I didn't want to mess with the system packages and such, so I didn't have my own build python, but install all the python packages I needed with pip.

Now this may be a much less common case now that conda has become the standard.

**Comment by astrofrog** [comment]
I guess the question is whether we trust the Numpy developers for example to make sure that different combinations of Numpy and Python versions work. If we can trust them on that, then if we test affiliated packages with say Numpy 1.8/Python 3.3 and Numpy 1.11/Python 3.5, then maybe that's enough, and we don't need to test e.g. Numpy 1.11/Python 3.3.

In other words, maybe the built-in combinations of Numpy/Python in conda are fine, and we don't need to worry about the other combinations, since we don't *really* expect issues to happen with Numpy 1.11/Python 3.3 that wouldn't have happened with Numpy 1.8/Python 3.3 or Numpy 1.11/Python 3.5, right? (because such an issue would be due to a weird interaction of Numpy 1.11 with Python 3.3, which presumbaly would be caught by the Numpy CI? (well Numpy 1.11 with Python 3.3 might be a bad example since Python 3.3 may not be supported for Numpy 1.11, but you get the idea)

**Comment by MSeifert04** [comment]
if a numpy version has problems with a python version that would require an upstream-fix, so I agree that we don't need to test numpy/python versions. But the problem is that a lot of packages depend on a specific numpy/python version. For example `astropy` and if one build with python 3.3 installs numpy 1.8 and therefore also installs the "most current" astropy 1.0.1 it's getting messy to find out if the package has problems with python 3.3, numpy 1.8 or astropy 1.0.1.

But given that these are the `conda` standards it's likely that someone actually uses this combination so testing it is a good thing (from the user-perspective) but messy to disentagle for developers...

**Comment by bsipocz** [comment]
I think this can be closed, ``ci-helpers`` now pip installs astropy is a too old version is picked up from conda, and ``astropy-ci-extras`` is also populated with a few old version combinations.
