### ISSUE TITLE
Remove astropy logo and mentions in top bar by default

### ISSUE THREAD

**Issue by astrofrog** [astropy/package-template#191]
By default, when people make a package using this template, the logo in the top left is astropy and there is also a link to astropy further along the right. I think the default logo should actually be empty and we shouldn't force the astropy branding on the logo if one is added. Only the actual astropy docs should say astropy in the top left.

**Comment by bsipocz** [comment]
@astrofrog - parts of this is already been proposed here: https://github.com/astropy/package-template/pull/182

**Comment by bsipocz** [comment]
and probably https://github.com/astropy/package-template/pull/163 takes care of the logo?

**Comment by astrofrog** [comment]
Yes, #182 does this - and I think we might also want to add a color option so that the logo defaults to all white (to not copy the astropy logo, though of course we can use the astropy 'branding' for affiliated packages).

**Comment by bsipocz** [comment]
I very much like the idea for affiliates to share the colors of astropy, though I agree that the template should show a way how to change it, or even default to something else while the new package is not yet affiliated. 
However I don't know how to change it, and don't have much time to figure it out now.

**Comment by astrofrog** [comment]
@bsipocz - don't worry about it, I'm sure someone else can do it at some point!

**Comment by bsipocz** [comment]
@astrofrog - photutils does it in a custom photutils.css file (along with changing the logo), but it would be nice to move those config options into docs/conf.py

**Comment by eteq** [comment]
I'm going to make a command decision to close this since it now says "package-template"

**Comment by bsipocz** [comment]
but it still has the astropy logo, hasn't it?
