### ISSUE TITLE
Change template package name

### ISSUE THREAD

**Issue by bsipocz** [astropy/package-template#192]
I think it would be clearer for the docs if we would call the template package directory `package-template` rather than `packagename`. 

E.g. the following in https://github.com/astropy/astropy/pull/5251 would be a useful addition, but it doesn't work for `'packagename'` as some of the config files have that as a variable to pick up the name of the package, while at other places it's considered the string name of the package.

```
#. Double check that you have changed all the ``'package-template'`` references
  in the configuration files to be <packagename>, the name of your package.
```

**Comment by astrofrog** [comment]
I don't think we should call the template package ``package-template`` because then there's the ambiguity of having to use ``-`` or ``_`` depending on context. However, we could consider other names that don't include a ``-``?

**Comment by bsipocz** [comment]
Sure, my only agenda is to find something that is not ``'packagename'``. Or vice-versa, use something else in the docs than ``'packagename'`` and then it can remain the name of the template package.

**Comment by astrofrog** [comment]
I think changing the docs would be preferable to changing the actual template, since it will cause some fun when merging in the changes to existing packages.

**Comment by bsipocz** [comment]
OK, then I'll go ahead and change the docs to use ``yourpackagename`` rather than ``packagename``.

**Comment by bsipocz** [comment]
Closing as this becomes obsolete with cookiecutter.
