### ISSUE TITLE
Typo in travis comment

### ISSUE THREAD

**Issue by dkirkby** [astropy/package-template#193]
The following commented-out line in `.travis.yml` has a typo (astopy should be astropy):

```
# - CONDA_CHANNELS='astopy-ci-extras astropy'
```

**Comment by dkirkby** [comment]
Related to this, I found that I had to use `CONDA_CHANNELS=astropy-ci-extras` in order to get the new tests using `env: ASTROPY_VERSION=lts` to pass.  Otherwise, they fail with mysterious errors about incompatible package versions, e.g.
```
The following specifications were found to be in conflict:
  - astropy 1.0* -> numpy 1.10*|1.9*
  - astropy 1.0* -> python 2.6*|3.3*|3.4*|3.5*
  - python 2.7*
```
(Mysterious because `python 2.7` is missing from the list of versions compatible with `astropy 1.0`).

**Comment by bsipocz** [comment]
Thanks @dkirkby for spotting the typo. Would you care to open a PR for it or shall I?

**Comment by bsipocz** [comment]
>Related to this, I found that I had to use CONDA_CHANNELS=astropy-ci-extras in order to get the new tests using env: ASTROPY_VERSION=lts to pass.

Indeed. Conda stopped building the 1.0.x branch a while ago, and they don't provide builds with older numpy versions either. 

So to help the testing of packages that depends on astropy we build conda packages for more combinations in ``astropy-ci-extras``. I see the point that more documentation would be better. As you have fresh eyes on the issue, maybe you could propose a place for it?

**Comment by dkirkby** [comment]
I can open the PR but I'm not sure what the changes should be yet: in addition to the typo, I believe that the following should be included in the default (instead of commented out):
```
- CONDA_CHANNELS='astopy-ci-extras'
```
in order to work out-of-the-box with these testing envs:
```
        - python: 2.7
          env: ASTROPY_VERSION=lts
        - python: 3.5
          env: ASTROPY_VERSION=lts
```
Do you agree?

**Comment by bsipocz** [comment]
OK, sounds reasonable. But if you comment out, maybe it's better to keep the astropy channel there as well (having a commented line, and a default one is more confusing I think.

**Comment by dkirkby** [comment]
That sounds good (unless adding the unused conda channel would slow down travis tests?)

**Comment by bsipocz** [comment]
No, it doesn't have any such effect.

**Comment by dkirkby** [comment]
Regarding the documentation of this package, most people start [here](http://docs.astropy.org/en/stable/development/affiliated-packages.html), but this lives under the astropy package so is separately versioned. I made some template docs suggestions in astropy/astropy#4054 a while ago, which probably got lost among the core pkg issues.

**Comment by bsipocz** [comment]
Closing as this got fixed with various PRs here.
