### ISSUE TITLE
long_description from setup.cfg is not used

### ISSUE THREAD

**Issue by saimn** [astropy/package-template#194]
The long description is actually obtained from the package's docstring, so simplest option would be to remove `long_description` from `setup.cfg`.

**Comment by pllim** [comment]
But not everyone put the long description there in the package docstring and it would not be fair to force this upon template users? Hmm.

**Comment by saimn** [comment]
It is not to force users but just to reflect the current state. 
I use the README for the long description so I changed the code for my own case. But the point here is that users can be confused because long_description from setup.cfg is not used currently.
Then, maybe some kind of parameter could be added to give different possibilities (from README, or __init__, or setup.cfg).

**Comment by pllim** [comment]
How about we leave the `long_description` in `setup.cfg` but add a comment that it is not necessary if the description is stored somewhere else? Not sure what is the cleanest approach here.

**Comment by saimn** [comment]
It is not *used* : https://github.com/astropy/package-template/blob/master/setup.py#L40

**Comment by pllim** [comment]
I know. I was suggesting that we include option in `setup.py` to actually use it, but also give the other alternatives. Like I said, I am not sure if this is not just further confusing the users.

**Comment by embray** [comment]
A common idiom is to use `long_description` if it's explicitly provided, but otherwise read the value for `long_description` from the README file.

**Comment by saimn** [comment]
Yep, I agree it would be a more reasonable than using the root package docstring. But this would be a breaking change for packages that use the template, how a change like this should be handled ?
BTW, I saw yesterday a blog post on pbr, which also use a setup.cfg, with support for more metadata: classifier, keywords, and description-file:
http://docs.openstack.org/developer/pbr/#setup-cfg
