### ISSUE TITLE
Don't use 2to3 by default ?

### ISSUE THREAD

**Issue by saimn** [astropy/package-template#195]
Now that there are plans to drop Python 2 support, I don't think using 2to3 should be the default option. For Astropy, this also requires that every sub-package has a `setup_package.py` file, just to define `requires_2to3()` and return False. (I didn't see a case where `requires_2to3()` returns True but maybe I missed it).

**Comment by pllim** [comment]
There is already a PR for this. See #93.

**Comment by saimn** [comment]
Ah thanks @pllim , I missed that.
