### ISSUE TITLE
Find a way to provide automated updates to users of the template

### ISSUE THREAD

**Issue by astrofrog** [astropy/package-template#197]
At the moment maintaining a package using the template is no trivial effort (as witnessed by the long instructions at http://docs.astropy.org/en/stable/development/affiliated-packages.html). Over time, it's become a pain to try and make sure all packages are up-to-date with the package template, and there is still a lot of repetition of code across packages, and I find myself doing the same tasks to update in different packages.

A little while back, I set up a script that automatically updates the `astropy_helpers` submodule and `ah_bootstrap.py`: https://github.com/astropy/astropy-tools/pull/13

It seemed like package maintainers liked this, since it was much less effort for them. This approach was inspired by conda-forge, where any updates to feedstocks on the infrastructure level are done by automated PRs.

I would like to brainstorm about whether we can do this for more infrastructure files. For instance, I think we could automate the updating of the following files:
- `ez_setup.py`
- `setup.py` - since with https://github.com/astropy/package-template/pull/129, I think the last of the custom content has been moved to `setup.cfg`
- `_astropy_init.py`
- `.gitignore` - if packages need specific additions to this file, there is no reason they can't add them to the package-template?
- `conf.py` (for the docs) - here we need to make sure we allow users to specify custom code though, so we could imagine having a `docs/conf_pre.py` and `docs/conf_post.py` (or a single file) that users edit with minimal content and the `conf.py` file is then a common file to all packages which runs the pre/post steps?

Then I think we should think about trying to automate the updating of `.travis.yml` and `appveyor.yml`. In many packages, the content is basically the same except for the package name and things like whether coveralls is enabled or not. Maybe we can figure out how to write a simple YAML file where users can set options for the CI YAML files and we auto-generate those files for them?

More generally, we could consider having a YAML file that also allows maintainers to opt in/out of auto-updating certain files and could also include the CI options. For instance, let's say we called it `.package_template.yml`, it could contain for instance:

```
auto_update:
  - astropy_helpers
  - ah_bootstrap.py
  - setup.py
  - conf.py

auto_ci:
  - travis
  - appveyor

ci:
  conda_dependencies:
    - scipy
    - matplotlib
  pip_dependencies:
    - wcsaxes
  coveralls: false
```

These are just ideas so far, but I'd be interested in feedback! I was thinking of maybe having a hangout to discuss this kind of idea if people are broadly in favor.

What I want to do is make sure that using the template provides _benefits_ (easy set-up of CI etc) as opposed to becoming a burden to maintain.

cc @bsipocz @larrybradley @adrn (as deputy maintainers) and @eteq @taldcroft @kelle (as coordinators)

**Comment by astrofrog** [comment]
For the initial set-up for new packages, it would also make sense to provide a simple script like ``sphinx-quickstart`` that asks the user questions and sets up the files accordingly. This would simplify the instructions hugely.

**Comment by adrn** [comment]
I like the idea of a quickstart-like setup script! 

I'm not sure how I feel about having a file that allows opting in/out of updates -- will have to think a bit about that and the other suggestions! 

I like the idea of having a hangout to discuss, but only after I can digest some ideas.

**Comment by saimn** [comment]
The `sphinx-quickstart` like script could be easily done with something like https://github.com/audreyr/cookiecutter : it uses jinja templates and will ask the needed values (with default values, and support for the activation of optional functionality).
Updating the template is more tricky, as it is difficult to be sure that the files have not been modified.

**Comment by pllim** [comment]
Quick start is fine, but I am :-1: on auto update. I wouldn't trust it not to undo my customization.

**Comment by astrofrog** [comment]
Just to be clear, what I'm suggesting is that some files should ideally not have any customization and therefore could be auto-updated - the bottom line is that for many of my packages I know I just want to use standard infrastructure files with no customization, and would appreciate to receive a PR with the updates to those files. But I understand that some people might want to customize some of the infrastructure files, hence why I'm suggesting this would be opt-in. The YAML file would essentially be used to say 'please open a PR to update these files'. You can always turn down the PR though.

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
