### ISSUE TITLE
Check whether setup_requires really needs to be defined

### ISSUE THREAD

**Issue by astrofrog** [astropy/package-template#209]
If so, setup_requires should include Cython if the package includes Cython code and the current version is a developer version. See https://github.com/astropy/package-template/pull/131 for a discussion of this.

A better solution might be to simply populate setup_requires in setup.py based on which extensions are being passed to setup.py. I'll work on a PR for that to see if it works. Or we can just check whether Cython files are present.

**Comment by cmccully** [comment]
Also, numpy often has to be installed before setup if you are using Cython as it often has to tell the c compiler where to find the numpy include files.

**Comment by pllim** [comment]
Irrelevant due to #438
