### ISSUE TITLE
Add tests_require to setup.cfg and setup.py

### ISSUE THREAD

**Issue by astrofrog** [astropy/package-template#210]
This could be done similarly to https://github.com/astropy/package-template/pull/208, but we should make sure it actually works (in a few simple experiments, I found that while the eggs do get created, the dependencies are not seen by the test process).

**Comment by pllim** [comment]
Done in #438

**Comment by astrofrog** [comment]
Just for the record, we actually added a ``test`` section in ``extras_require`` rather than use ``tests_require`` - the latter aren't really well supported by testing tools
