### ISSUE TITLE
Add a "support LTS" option in the cookiecutter.json

### ISSUE THREAD

**Issue by Cadair** [astropy/package-template#227]
This would allow us to move parts of the template faster to support changes that are not in the LTS.

see #211

**Comment by pllim** [comment]
We moved PY2 stuff to a different branch, so this is indirectly resolved?

**Comment by bsipocz** [comment]
It may still be an option to opt in "support LTS" in a generic LTS sense. Not sure in practice it has any significant priority. If anyone feels strongly about it, PRs are welcome.

**Comment by pllim** [comment]
We have no more LTS with https://github.com/astropy/astropy-APEs/blob/main/APE21.rst
