### ISSUE TITLE
Getting-Started page refers to now-non-existent MANIFEST.in

### ISSUE THREAD

**Issue by aphearin** [astropy/package-template#244]
The extremely useful and clearly written http://docs.astropy.org/en/stable/development/affiliated-packages.html page appears to have fallen slightly behind development. Step 3 of the **Managing the template files manually** section has the following instructions, which appear to no longer be relevant: 

```
# MANIFEST.in specifies which files to include in a tar file
release. Change all ``'packagename'`` text to be the name of your
package, <packagename>.
cp ../template/MANIFEST.in .
```

**Comment by bsipocz** [comment]
@aphearin - The default branch has been changed to ``cookiecutter``, it is not supposed to be used directly. You can get the old pre-cookiecutter version if you change back to ``master``, or I assume the ``rendered`` branch has the now updated things, though I'm not sure what opt-ins it was rendered.

cc @Cadair - we need to wrap up the cookiecutter docs at some point...

**Comment by aphearin** [comment]
Ahh, I see. This is the first time I noticed the `cookiecutter` migration in action.

FYI: I now use the astropy package-template for every scientific project I work on that has reached a mature stage. I would start using the `cookiecutter` machinery as soon as the documentation becomes available, but for now I will change back to `master` due purely to the fact that the documentation for the new `cookiecutter` branch is not yet up and running. I'll happily serve as a guinea pig for the docs once they're up.
