### ISSUE TITLE
cookiecutter license is always 3-clause BSD (but inconsistent w/setup.cfg)

### ISSUE THREAD

**Issue by eteq** [astropy/package-template#248]
Right now, if I do cookiecutter as-is, I'm given an option of licenses, but the ``license/LICENSE.rst`` file is *always* the 3-clause BSD.  (It also has "Astropy Team" in the middle of it, which is certainly wrong, although probably just requires a one-line fix).  So if I choose "GNU GPL", the metadata says it's GPL, but the LICENSE file does *not*.

I don't know cookiecutter enough to fix this.  @Cadair, is this easy?  E.g., can we provide multiple license templates and have just the right one get put in the final generated repo?

**Comment by eteq** [comment]
(Note this is *not* the same as #243, as that's about the year rather than the license itself)

**Comment by Cadair** [comment]
Yes, I knew about this but hadn't opened an issue. It should be easy enough to fix in a post-render hook.
