### ISSUE TITLE
parent project is sunpy in travis build

### ISSUE THREAD

**Issue by eteq** [astropy/package-template#250]
@Cadair - I noticed the following in the `.travis.yml`:
```
- EXTRA_CONTEXT='_parent_project=sunpy'
```

Is that a left-over from somewhere?  That is, should that be astropy, or absent entirely?

**Comment by bsipocz** [comment]
What is this ``EXTRA_CONTEXT`` btw, I haven't found any mention of it in the travis docs.

**Comment by eteq** [comment]
@astrofrog might know too?

**Comment by Cadair** [comment]
`EXTRA_CONTENT` is the way I am setting options to cookiecutter for Travis. (i.e. overriding options the user can change) see: https://cookiecutter.readthedocs.io/en/0.9.1/advanced_usage.html#injecting-extra-context

the specific `_parent_project=sunpy` flag is to test that the package template renders if the hidden (not asked to the user) option is changed. (SunPy will be using it).

**Comment by bsipocz** [comment]
Nice trick, thanks for the explanation @Cadair!

**Comment by astrofrog** [comment]
I think this warrants a comment in .travis.yml, so I'm going to re-open this
