### ISSUE TITLE
Rendered branch should have astropy-helpers

### ISSUE THREAD

**Issue by bsipocz** [astropy/package-template#253]
The current ``rendered`` branch example doesn't have astropy-helpers as a git submodule, that should be fixed. See discussion in #247. 

#252 is also related.

**Comment by Cadair** [comment]
hmmm, this looks like it could be a pain to extract the version of astropy_helpers out of the cookiecutter config. If we just want to add the submodule manually in the `travis_deploy.sh` script it should be ok.
