### ISSUE TITLE
missing ah_bootstrap.py

### ISSUE THREAD

**Issue by hamogu** [astropy/package-template#258]
I used cookiecutter to get the template, but the ah_bootstrap.py seems to be missing (it's required in line 4 of the setup.py)

**Comment by hamogu** [comment]
No. I added astropy_helpers manually. I don't think I have gitpython installed ... is that listed in the requirements? If it is in fact required, I suggest throwing an error if it's not available.

**Comment by bsipocz** [comment]
@Cadair - ah is not added in the rendered version either, so we should indeed list it some requirement file

**Comment by Cadair** [comment]
It wont help the rendered version because of the way I copy the files into the repo to maintain history.

We need the install instructions to say you need gitpython.

**Comment by eteq** [comment]
@bsipocz @Cadair - clarify for me here: are you saying `ah_boostrap.py` should *not* be in the rendered branch?  Remeber that this will also be used for helpers users to *maintain* their package.  Doesn't that mean it has to be there so that they can download it whenever the boostrap script is changed?

**Comment by bsipocz** [comment]
I think it **should be** in the rendered branch, but it's not there atm which is a bug. We also need to do something with "master", e.g. rename it to legacy or something...

**Comment by eteq** [comment]
Ah, ok.  @Cadair, it sounds like you know what the problem is?  Any chance you can just do a quick fix or at least give a hint as to what the oddness is in the "way I copy files into the repo"?

(will make a separate issue re "master")

**Comment by eteq** [comment]
(To be clear, this is a pretty major hurdle for those wanting to use it, so high priority... If you don't know what the helpers are or what bootstrapping is, you're almost certainly out of luck!)
