### ISSUE TITLE
Change "master" branch name?

### ISSUE THREAD

**Issue by eteq** [astropy/package-template#263]
As pointed out in https://github.com/astropy/package-template/issues/258#issuecomment-321884404, "master" is now a rather confusing name post-cookiecutter.  I like @bsipocz's suggestion of "legacy".  If others agree I can go ahead and just change the name.

**Comment by bsipocz** [comment]
Ideally we need to update the docs in astropy core to change the reference from 'master' to the 'rendered' branch.

**Comment by bsipocz** [comment]
This issues is now postponed as master is the default branch again. Revisit once we're back at cookiecutter.
