### ISSUE TITLE
Update entry point configuration to be more general

### ISSUE THREAD

**Issue by drdavella** [astropy/package-template#283]
Currently `setup.cfg` can only be used to configure entry points for `console_scripts`. However, packages may also want to configure other entry points in `setup.cfg`, which is not currently supported. This might be difficult to do without breaking compatibility with the current scheme.

This is particularly relevant to the discussion in https://github.com/astropy/astropy/issues/6623, and also to https://github.com/astropy/astropy/pull/6883.

**Comment by pllim** [comment]
Irrelevant due to #438
