### ISSUE TITLE
plot with data in package

### ISSUE THREAD

**Issue by tcassanelli** [astropy/package-template#284]
I'm having problems with the docs. What I need to do is to generate a plot from a source file, stored in my package, `example0.fits`, so far what I can do is to read the file, in some environments, unfortunately if I want to plot it I cannot :confused:

What I'm doing to import the file is the following (writing in .rst)
```python
>>> import pyoof
>>> from scipy import interpolate
>>> import matplotlib.pyplot as plt
>>> from astropy.utils.data import get_pkg_data_filename
>>> oofh_data = get_pkg_data_filename('pyoof/data/example0.fits')

>>> data_info, data_obs = pyoof.extract_data_pyoof(oofh_data)
>>> [name, obs_object, obs_date, pthto, freq, wavel, d_z, meanel] = data_info
>>> [beam_data, u_data, v_data] = data_obs

>>> print(u_data[0])
[-0.00089586 -0.0008772  -0.00085854 ...,  0.00085854  0.0008772
  0.00089586]
>>> print(v_data[0])
[-0.00089586 -0.00089586 -0.00089586 ...,  0.00089586  0.00089586
  0.00089586]
>>> print(beam_data[0])
[  834.79919434   532.3102417   -272.52365112 ...,   839.55853271
   132.47489929 -1083.75915527]
```

and it works, reading and handling data in the `>>>` environment isn't a problem. I also executed test,  
```bash
python setup.py test -t docs/index.rst
```
And it woked out fine. The problem comes when I want to plot something, by default, using the plot environment for .rst `.. plot::` then I type the same routine,

```python
import pyoof
from scipy import interpolate
import matplotlib.pyplot as plt
from astropy.utils.data import get_pkg_data_filename
oofh_data = get_pkg_data_filename('pyoof/data/example0.fits')

data_info, data_obs = pyoof.extract_data_pyoof(oofh_data)
[name, obs_object, obs_date, pthto, freq, wavel, d_z, meanel] = data_info
[beam_data, u_data, v_data] = data_obs

u_data, v_data = np.degrees(u_data), np.degrees(v_data)
vmin = np.min(beam_data)
vmax = np.max(beam_data)

fig, ax = plt.subplots(ncols=3)
for i in range(3):
    # new grid for beam_data
    u_ng = np.linspace(u_data[i].min(), u_data[i].max(), 300)
    v_ng = np.linspace(v_data[i].min(), v_data[i].max(), 300)

    beam_ng = interpolate.griddata(
        # coordinates of grid points to interpolate from.
        points=(u_data[i], v_data[i]),
        values=beam_data[i],
        # coordinates of grid points to interpolate to.
        xi=tuple(np.meshgrid(u_ng, v_ng)),
        method='cubic'
        )
    extent = [u_ng.min(), u_ng.max(), v_ng.min(), v_ng.max()]
    ax[i].imshow(beam_ng, extent=extent, vmin=vmin, vmax=vmax)
    ax[i].contour(u_ng, v_ng, beam_ng, 10)
```
I get a long error line, which ends with `urllib.error.HTTPError: HTTP Error 404: Not Found`. The previous environment (`>>>`) in the .rst file was able to find the file in the package, but the `.. plot::` environment isn't able (making a plot without external data works fine also). 

What I also noticed is that the problem happens only when the file is imported in the `.. plot::` environment.

```python
from astropy.utils.data import get_pkg_data_filename
oofh_data = get_pkg_data_filename('pyoof/data/example0.fits')
```

This returns the same error/warning as before.

You can find my package [here](https://github.com/tcassanelli/pyoof/). For the docs file that I'm compiling go to [index.rst](https://github.com/tcassanelli/pyoof/blob/master/docs/index.rst) and the data file is [here](https://github.com/tcassanelli/pyoof/tree/master/pyoof/data) . Then I simply execute
```bash
python setup.py build_docs
```

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
