### ISSUE TITLE
cookie-cutter wants local copy of ah_bootstrap to install my package.

### ISSUE THREAD

**Issue by SaOgaz** [astropy/package-template#304]
Hi,

I was testing out the new cookie-cutter version of the template package, using the following version:
``cookiecutter gh:astropy/package-template --checkout cookiecutter``

Answered the astropy-helpers question like so (I realize now this is probably not a valid answer):
``astropy_helpers_version [v2.0.2]: n``

Now's the part I'm not sure about, at some point something installed astropy_helpers (maybe even me?) version 2.0 into my conda environment, but not actively a copy of it into the package I was running cookie-cutter on.

When I tried to run ``python setup.py develop`` after finishing up with cookie-cutters I got the following error:

```
(stisdev) moka:stistools ogaz$ python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import ah_bootstrap
ModuleNotFoundError: No module named 'ah_bootstrap'
```

@crawfordsm helped me grab this module, and then I was able to install my package:
```
git submodule add https://github.com/astropy/astropy-helpers.git astropy_helpers
cp astropy_helpers/ah_bootstrap.py .
```

@crawfordsm said I should post this all here as it's due to a bug.  So far everything else is working great for me.

**Comment by bsipocz** [comment]
@SaraOgaz - I'll look into this either tonight or tomorrow. But first though, there is no scenario when you need astropy-helpers installed into your environment. I don't think it would mess up anything, but better not giving it a chance.

**Comment by SaraOgaz** [comment]
@bsipocz yeah, I reeeaaally don't remember how I ended up with an install of it... I don't remember installing it myself but this environment's been through the wringer with me trying to get stuff working, so who knows.
