### ISSUE TITLE
Rendered version should be more inclusive than users

### ISSUE THREAD

**Issue by bsipocz** [astropy/package-template#314]
For the rendered version we should have everything opt in, including listing all options for licences, etc. This rendering shouldn't end up with the users though, so ideally will be created with private options like "_all".

**Comment by Cadair** [comment]
This is now done for licence. Do you have specific other examples?

**Comment by bsipocz** [comment]
no, I have to try out it to find more of these, or better, we'll see if people try it out tomorrow.

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
