### ISSUE TITLE
Remove ez_setup

### ISSUE THREAD

**Issue by bsipocz** [astropy/package-template#315]
It has been already been removed from astropy-helpers, we don't really use it anywhere for packaging, so the cookicutter rendering should not try to copy it over either.

**Comment by astrofrog** [comment]
By the way this requires ``ah_bootstrap.py`` to no longer use it (which e.g. astropy-helpers v2.0.x does)

**Comment by Cadair** [comment]
we could have the post hook remove it if the astropy helpers version is >= 3 ?

**Comment by bsipocz** [comment]
I'm OK backporting that PR if there is an agreement on it. The removal of ez_setup was a long standing issue there and should really not use much trouble.

**Comment by astrofrog** [comment]
Done in https://github.com/astropy/package-template/pull/339
