### ISSUE TITLE
Feedback from a novice install using new cookiecutter documentation

### ISSUE THREAD

**Issue by ceb8** [astropy/package-template#329]
**Technical difficulties**
- Astropy "documentation about this template" link is broken
- I had to pip install *click* and *gitpython* packages.
  Some other people should try this and see if it is just a problem with my environment, however I was able to successfully conda install other packages no problem, so it might be a wider issue. I am using Python 3.6.5, and conda 4.0.6, and was installing from the conda-forge channel.
- In the readme the command is quoted as `cookiecutter gh:astropy/package-template` while in the astropy instructions, it's `cookiecutter -c cookiecutter gh:astropy/package-template.` Both seem to work? But the discrepancy is slightly confusing.
- There is still a default git repository even if you click 'false' for GitHub Sphinx plug in, when presumable it should just be empty.

**More subjective experiences with documentation**
- It wasn't super clear to me which link let to the "How To" type of instruction
- It would have been nice to have it specified somewhere that a new directory will be created so you don't need to be in an empty directory or the directory with your code or anything
- The descriptions for "package name" and "module name" are kind of confusing, it isn't clear that "package name" is what the directory will be called and "module name" is what you will import when it is installed.
- I think it would be helpful to provide links in the related keyword descriptions to:
   - Sphyinx html_themes docs
   - GitHub Sphinx plug-in docs
   - Travis docs
   - Apveyor docs
   - Readthedocs docs
- The "any of the values can still be manually updated"  link leads to a page that is not obviously about how to do that, it's about updating your package generally, but didn't seem to have specific instructions about how to update some of those initial decisions.
- The next steps don't include anything about the structure of the directory you just created or how to install your new package or anything.  It seems like familiarity is assumed on the part of the developer, I don't know if that's an assumption you want to make.

**Comment by pllim** [comment]
So, what's the feedback? :sweat_smile:

**Comment by ceb8** [comment]
@pllim I didn't know hitting enter created the issue!

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
