### ISSUE TITLE
configparser needed for Read the Docs

### ISSUE THREAD

**Issue by bmorris3** [astropy/package-template#334]
The default Read The Docs build requires configparser, but it doesn't appear in the .rtd-environment.yml file. Should we add
```
    - pip:
        - configparser
```
to the template?

**Comment by dkirkby** [comment]
I had the same issue but wondered if `configparser` shouldn't be installed via conda.  However, when I tried to `conda install configparser`, I got:
```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - configparser
  - poyo
```
It looks like `poyo` is a requirement of cookiecutter.

**Comment by Cadair** [comment]
Wait wat. I thought configparser was stdlib. 

This shouldn't be an issue under Python 3.5, as apparently the pip package configparser is a backport from 3.5 to previous versions.

**Comment by bsipocz** [comment]
yeah, but still, do we handle the <3.5 case gracefully?

**Comment by dkirkby** [comment]
Perhaps the problem is that RTD defaults to a py27 env?  Adding instructions to select "Cython 3.x" under Advanced Settings on the [Next Steps](http://docs.astropy.org/projects/package-template/en/latest/nextsteps.html) would help, but I don't think that guarantees 3.6, since I am now triggering this setup.py check:
```
ERROR: skysim requires Python 3.6 or later
```

**Comment by bsipocz** [comment]
@dkirkby - This definitely looks like a bug, there seems to be a few left with the new machinery. Thank you for the feedback both here and in #347

**Comment by pllim** [comment]
You can ask RTD to build with Python 3. It is in your RTD project admin settings.

**Comment by pllim** [comment]
@dkirkby , if RTD is not respecting admin settings, please open an issue with them at https://github.com/rtfd/readthedocs.org/issues .

**Comment by dkirkby** [comment]
@pllim Do you see evidence that RTD is not respecting admin settings in [this build log](https://readthedocs.org/projects/skysim/builds/7384015/)?

**Comment by weaverba137** [comment]
Sorry to jump in here, but I certainly do.  If you look at the raw logs, you'll see that it is using Python 2.  For example, this line near the bottom:
```
Requirement already up-to-date: docutils>=0.11 in /home/docs/checkouts/readthedocs.org/user_builds/skysim/conda/latest/lib/python2.7/site-packages (from recommonmark)
```

**Comment by dkirkby** [comment]
Thanks Ben, I will open an issue with RTD.

**Comment by bmorris3** [comment]
@dkirkby I'd love to hear any feedback you get in this thread, my docs are forever stalled :(

**Comment by bmorris3** [comment]
I find that I can solve the problem if I add the following two lines to the `.rtd-environment.yml` file: 

```
dependencies:
    - python=3.5
    - sphinx-astropy
```

**Comment by bmorris3** [comment]
I think this means 

1) effectively cookie cutter shouldn't offer py2.7 support anymore
2) we should explicitly put the selected python version in the dependencies yml file
3) I could use the help of a cookie cutter pro to make the PR that does this, cc @Cadair?

**Comment by astrofrog** [comment]
So just to be clear, the RTD build can use Python 3 even for a package that supports Python 2 and 3 - it just means we can't support Python 2-only packages (which we don't anyway)
