### ISSUE TITLE
Documentation: I don't understand what cookiecutter does

### ISSUE THREAD

**Issue by keflavich** [astropy/package-template#335]
The main documentation page doesn't say exactly what cookiecutter does or where you should run it.  This might only affect me, because I was used to the old package-template, but I expected that you should run cookiecutter in the directory of an existing repository.  That clearly is not the case; I think you're supposed to run it in some random location and create the whole repository from scratch.

It would be helpful to have a guide showing how to migrate an existing package into an astropy-package.  Maybe the answer is just 'make cookie cutter package, copy things in from other one', but that's not obvious to me.

**Comment by keflavich** [comment]
Oh, also, it really sucks having to answer all the questions from scratch when cookiecutter fails.

**Comment by bsipocz** [comment]
@keflavich - We still don't have a good enough infrastructure to help updating already existing packages, so this is a very valuable feedback that we should not forget about it.

In the meantime,  the master branch is there with a rendered version, that is basically looks like the old package-template, and you can use that as you used the template before.

**Comment by eteq** [comment]
> In the meantime, the master branch is there with a rendered version, that is basically looks like the old package-template, and you can use that as you used the template before.

(a good point that it should say this in the readme, though!)

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
