### ISSUE TITLE
Add opt in for nitpicky docs mode to form

### ISSUE THREAD

**Issue by bsipocz** [astropy/package-template#337]
Currently the nitpicky part is just dumped into the rendered `docs/conf.py` file commented out rather than configured by cookiecutter. It should either be there uncommented, or not there based on the config.

**Comment by astrofrog** [comment]
I think we should just have it enabled by default for new packages, right? Older packages can always comment it out if they can't cope with it?

**Comment by bsipocz** [comment]
yes, I think enabling by default is the right thing to do.

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
