### ISSUE TITLE
Travis problems

### ISSUE THREAD

**Issue by dkirkby** [astropy/package-template#347]
After enabling travis (and RTD), I ran into a few problems with a vanilla cookiecutter template.

1. sphinx-astropy is not declared as a dependency.  I fixed this by adding it to `CONDA_DEPENDENCIES` in `.travis.yml`.  I suspect it should also be added to `.rtd-environment.yml`.

2. I specified a min python version of 3.6, but the travis config stills tests old numpy versions against 3.5:
```
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.10
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.11
```
I just removed these lines, but perhaps 3.5 should be replaced with 3.6 instead?

**Comment by dkirkby** [comment]
More on sphinx-astropy: looking at my travis logs, I see that the following is failing:
```
conda install -c astropy sphinx-astropy
```
The test still passes since it falls back to a pip install, but isn't this conda install [supposed to work](https://anaconda.org/astropy/sphinx-astropy) and preferred?

I just noticed that sphinx-astropy-1.0 is available from the conda-forge channel. Should that be added the travis `CONDA_CHANNELS`?

**Comment by bsipocz** [comment]
Weird, `sphinx-astropy` should have been picked up from the astropy channel: https://anaconda.org/astropy/sphinx-astropy

**Comment by dkirkby** [comment]
Perhaps it is just me.  Is anyone else able to reproduce this failure?
```
%  conda install -c astropy sphinx-astropy
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - sphinx-astropy
  - sphinx-gallery

Current channels:

  - https://conda.anaconda.org/astropy/osx-64
  - https://conda.anaconda.org/astropy/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch
```

**Comment by pllim** [comment]
I have no problem with conda finding it both on Linux and Windows. What is your OS?

**Comment by dkirkby** [comment]
Conda is looking in the `astropy/osx-64` channel (see the log above).

**Comment by dkirkby** [comment]
Travis builds on `linux64` are also failing to conda-install sphinx-astropy, but for a different reason (missing sphinx-gallery):
```
PackageNotFoundError: Packages missing in current channels:
            
  - sphinx-astropy -> sphinx-gallery

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/astropy/linux-64
  - https://conda.anaconda.org/astropy/noarch
  - https://conda.anaconda.org/astropy-ci-extras/linux-64
  - https://conda.anaconda.org/astropy-ci-extras/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
```
The full log is [here](https://api.travis-ci.org/v3/job/395535488/log.txt).

**Comment by astrofrog** [comment]
@dkirkby - for your local issues, what conda version do you have? If your conda is too old it won't see recent conda packages. You could try:

```
conda update -n root conda
```

then see if that now works locally.

**Comment by dkirkby** [comment]
Thanks for the suggestion @astrofrog.  I was only a little out of date:
```
    certifi: 2018.4.16-py36_0  --> 2018.8.13-py36_0
    conda:   4.5.8-py36_0      --> 4.5.9-py36_0
    openssl: 1.0.2o-h26aff7b_0 --> 1.0.2p-h1de35cc_0
```
After the update, `conda install -c astropy sphinx-astropy` is still failing the same way.

I attached the [output](https://github.com/astropy/package-template/files/2290199/install.log) from:
```
conda install -vvv -c astropy sphinx-astropy >& install.log
```
in case anyone is willing to take a closer look (I didn't see anything obvious).

**Comment by astrofrog** [comment]
We have a similar issue with sphinx-astropy here: https://travis-ci.org/astropy/package-template/jobs/416380859
