### ISSUE TITLE
Difficulty finding astropy.helpers.plugins

### ISSUE THREAD

**Issue by bmorris3** [astropy/package-template#348]
I'm working on a [package](https://github.com/bmorris3/stash) built from the package-template (since the cookiecutter update), and when I run `python setup.py test`, I get the following error: 
```
Traceback (most recent call last):
  File "/Users/bmmorris/.local/lib/python3.5/site-packages/_pytest/config.py", line 342, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/private/var/folders/b3/hq8c10h90xdc3mxwlk53tvzm0000gn/T/stash-test-juou8krc/lib.macosx-10.6-x86_64-3.5/stash')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/bmmorris/.local/lib/python3.5/site-packages/_pytest/config.py", line 373, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/private/var/folders/b3/hq8c10h90xdc3mxwlk53tvzm0000gn/T/stash-test-juou8krc/lib.macosx-10.6-x86_64-3.5/stash/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/bmmorris/.local/lib/python3.5/site-packages/_pytest/config.py", line 379, in _importconftest
    mod = conftestpath.pyimport()
  File "/Users/bmmorris/.local/lib/python3.5/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/Users/bmmorris/.local/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/private/var/folders/b3/hq8c10h90xdc3mxwlk53tvzm0000gn/T/stash-test-juou8krc/lib.macosx-10.6-x86_64-3.5/stash/conftest.py", line 14, in <module>
    from astropy.tests.plugins.display import PYTEST_HEADER_MODULES, TESTED_VERSIONS
ImportError: No module named 'astropy.tests.plugins'
ERROR: could not load /private/var/folders/b3/hq8c10h90xdc3mxwlk53tvzm0000gn/T/stash-test-juou8krc/lib.macosx-10.6-x86_64-3.5/stash/conftest.py
```
with astropy version `3.0.dev19880`, pytest version `3.6.2`. Has anyone else seen this before? I've tried hardcoding into `conftest.py`: 
```python
if True:
    from astropy.tests.pytest_plugins import *
```
but that hasn't seemed to help, yielding a much longer traceback ending in: 
```
ValueError: option names {'--doctest-plus'} already added
```

**Comment by bmorris3** [comment]
I was able to get the tests working by removing the import block currently in `conftest.py` and replacing it with: 
```python
from astropy.tests import pytest_plugins as astropy_pytest_plugins
```

**Comment by bsipocz** [comment]
Don't you get the deprecation warning? This should really work out of the box 😞

**Comment by drdavella** [comment]
Just curious but is there any chance you have an older version of `astropy` also installed in the same environment?

**Comment by bmorris3** [comment]
@drdavella – That's entirely possible. What's the best way to check?

**Comment by drdavella** [comment]
You need to look under the `site-packages` directory for your environment, and do something like the following:

`ls -d /path/to/environment/lib/python{VERSION}/site-packages/astropy*`

Since you have a development version of Astropy, I'd expect to see a file named `astropy.egg-link` under that directory. If there are other Astropy directories, it indicates you might have older versions installed as well.

**Comment by bmorris3** [comment]
@drdavella I found and deleted all versions except astropy 3.0.3, and now the cookiecutter code works without modification. Thanks for the tip!

**Comment by drdavella** [comment]
@bmorris3, happy to help! Feel free to close this issue 😄 .
