### ISSUE TITLE
python setup.py test doesn't run doctests

### ISSUE THREAD

**Issue by weaverba137** [astropy/package-template#35]
My affiliated package follows the template, but `python setup.py test` doesn't run the doctests in my code, but `packagename.test()` does run them, provided I have a pytest.ini file.  How do you turn on doctests?  I'd like to include the doctests in the Travis build.

**Comment by astrofrog** [comment]
Done in https://github.com/astropy/package-template/commit/04e308081224524bcd8fe6429b2e3b4aaaef6ff4
