### ISSUE TITLE
Enable coverage on all builds?

### ISSUE THREAD

**Issue by astrofrog** [astropy/package-template#367]
For the core astropy package, including coverage testing has a significant performance impact, but for other packages this won't necessarily be the case. We could consider adding ``--coverage`` to all builds by default instead of having a dedicated coverage build.

**Comment by pllim** [comment]
I definitely set it up by default for a few packages, so this is feasible in some cases. But maybe add a comment to discuss when you don't want to do that?

**Comment by pllim** [comment]
I think this idea was rejected in review of #438
