### ISSUE TITLE
Use codecov instead of coveralls?

### ISSUE THREAD

**Issue by astrofrog** [astropy/package-template#368]
Codecov is easier to set up than coveralls and produces nicer results these days. Should we switch to using that by default in the template? Or maybe we can make it a choice?

**Comment by pllim** [comment]
Choice is nice but also adds maintenance burden. I opt for Highlander style ("there can be only one").

**Comment by Cadair** [comment]
+:100: to codecov. It's just better in like every way

**Comment by bsipocz** [comment]
another vote for codecov, and I'm also very much supportive for a year now to switch the main repo to codecov as well.

**Comment by pllim** [comment]
If astropy/astropy#7879 is merged, similar changes there can be ported over here.

**Comment by bsipocz** [comment]
@pllim - yes, let's make that happen, we need one more approval for that PR and you're in the right place to make that happen by showing up in the right office :trollface:

**Comment by pllim** [comment]
Done in #449
