### ISSUE TITLE
Don't install LaTex

### ISSUE THREAD

**Issue by astrofrog** [astropy/package-template#369]
I think we can remove the following apt packages from Travis:

```
            - texlive-latex-extra
            - dvipng
```

because I think that we now use mathjax.

**Comment by bsipocz** [comment]
I was also experimenting with only installing the extra apt package, needed for the docs build, only for the docs build. It should work, but it doesn't yet. Anyway, once I figured out the details, I would add those changes to the template as well.

**Comment by astrofrog** [comment]
It seemed to work here: https://github.com/spacetelescope/mosviz/pull/129

**Comment by bsipocz** [comment]
Oh, sure. What I meant is is more like this, where apt install should work from the matrix, but I yet to figure out the right syntax (https://github.com/bsipocz/astroquery/blob/travis_add_np114/.travis.yml#L86)

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
