### ISSUE TITLE
_astropy_init.py is not python3 only

### ISSUE THREAD

**Issue by bsipocz** [astropy/package-template#383]
even when python2.7 is not supported.

Shall we have two version of the file, or messing with the content with some templating?

@Cadair @astrofrog @pllim

**Comment by Cadair** [comment]
Should be possible to template out bits like we have done elsewhere, or we just drop 2.7 :grin:

**Comment by bsipocz** [comment]
I'm in favour of the latter. No new packages should start at this point supporting it, and existing ones should seriously consider dropping support...

**Comment by pllim** [comment]
We dropped PY2, right? Is this still an issue?

**Comment by astrofrog** [comment]
Looks like it's not an issue, I don't see any Python 2.7 code in ``_astropy_init.py`` anymore
