### ISSUE TITLE
Formatting of disclaimer

### ISSUE THREAD

**Issue by astrofrog** [astropy/package-template#390]
For some reason the links don't work in the italic text:

<img width="980" alt="screenshot 2019-01-17 at 11 18 43" src="https://user-images.githubusercontent.com/314716/51315332-d6314a00-1a49-11e9-87f8-9acc60e9056e.png">

Removing the italics fixes it.

**Comment by pllim** [comment]
Why not a PR? :wink:

**Comment by astrofrog** [comment]
Too much to do, too little time!
