### ISSUE TITLE
error when running setup.py test

### ISSUE THREAD

**Issue by wkerzendorf** [astropy/package-template#394]
I get this error when running `python setup.py test` in python3.6 with helpers 3.1. it goes away when I run the same command again. Appears sometimes. 
```python
  File "/Users/wkerzend/python/tardis/astropy_helpers/astropy_helpers/version_helpers.py", line 281, in generate_version_py
    imp.reload(version_module)
  File "/Users/wkerzend/miniconda/envs/tardis3/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/Users/wkerzend/miniconda/envs/tardis3/lib/python3.6/importlib/__init__.py", line 159, in reload
    name=parent_name) from None
ImportError: parent 'tardis' not in sys.modules
```
[tardis_package_versions.txt](https://github.com/astropy/package-template/files/2886044/tardis_ah_fail.txt)

**Comment by astrofrog** [comment]
I'm not sure why this is happening, but the code that is triggering this will be gone in the next release of astropy-helpers. Does this happen only with 3.6?

**Comment by wkerzendorf** [comment]
Haven't tested any other versions yet. attaching environment file. but don't worry -if it goes away that's fine.

**Comment by pllim** [comment]
`python setup.py test` is no longer the way to go with #438 merged.
