### ISSUE TITLE
Failing RTD build

### ISSUE THREAD

**Issue by bmorris3** [astropy/package-template#397]
I'm trying to build the docs on a [package](https://github.com/bmorris3/fleck) I'm developing based on the package template, and I get the following build error when RTD runs `conda env create --quiet --name latest --file /home/docs/checkouts/readthedocs.org/user_builds/fleck/checkouts/latest/.rtd-environment.yml`: 

```
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - sphinx-astropy
  - sphinx-gallery
```

Could be related to #387?

**Comment by pllim** [comment]
You need to add those two packages to your RTD pip requirements? At some point, they were take out of helpers. Did you just updated your helpers or something?

**Comment by bmorris3** [comment]
Do you mean [like this](https://github.com/bmorris3/fleck/blob/master/.rtd-environment.yml#L13-L15)? Because I tried and it didn't work.

**Comment by pllim** [comment]
You can try their v2 format: https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by pllim** [comment]
Also check your RTD admin settings.

**Comment by pllim** [comment]
Oh, wait, don't use conda on RTD. Use pip.

**Comment by bmorris3** [comment]
I'm not sure I follow – where can I specify conda instead of pip?

**Comment by pllim** [comment]
Like this: https://docs.readthedocs.io/en/stable/config-file/v2.html#conda

Your original comment above mentioned conda.

**Comment by bmorris3** [comment]
As @pllim suggested, switching some dependencies to pip solved the problem, like so: 
```
dependencies:
    - python>=3.5
    - numpy
    - astropy
    - Cython
    - pip:
       - matplotlib
       - sphinx-astropy
       - batman-package
       - shapely
```

**Comment by bsipocz** [comment]
pip these days are faster than conda, so the suggestion here was to use pip _only_.
