### ISSUE TITLE
Revise recommended CI jobs

### ISSUE THREAD

**Issue by bsipocz** [astropy/package-template#402]
I feel that rather than suggesting to test with numpy prereleases low traffic packages should actually test against the dev version, or nightly builds when available.

Also, for good measure, I think the template shouldn't allow-to fail the flake8 job by default, and should update the numpy versions being tested, etc.

**Comment by pllim** [comment]
Or maybe this is a good excuse to switch to Azure altogether... or is that too ambitious?

**Comment by bsipocz** [comment]
@pllim - providing azure templates would be a very much welcomed addition.

**Comment by bsipocz** [comment]
I leave this issue open for now as there is space for improvement for adding either azure or circleCI or both of their configs.

**Comment by pllim** [comment]
Update: "Nightly" build (actually weekly?) of Numpy is available and being used in the core. See astropy/astropy#10288

Recently, @nmearl ran into problem building Numpy dev from source using this template, so changing to "nightly" would be a big plus.

Also, I see that I kinda volunteered above? LoL. I am reading up on Actions but I won't assign this to myself (yet) in case I don't get far with it.

**Comment by pllim** [comment]
Update: I think the clean-up was actually mostly done in #408, so #462 to add numpy wheel would actually completely resolve this.

Also, moving to Azure/Actions is out of scope and can be a separate PR/issue for the future. Should probably wait and see how astropy/astropy#8445 goes first.
