### ISSUE TITLE
Don't default to docs layout with a sub-directory for the package

### ISSUE THREAD

**Issue by astrofrog** [astropy/package-template#419]
The docs layout in:

https://github.com/astropy/package-template/blob/cookiecutter/%7B%7B%20cookiecutter.package_name%20%7D%7D/docs/index.rst

was originally used because the template was for use (initially) by a number of packages that might end up being merged into the core. This is very much no longer the case, so we should default to just having the top-level docs in ``docs``, not ``docs/packagename``

**Comment by Cadair** [comment]
I am sad I only have one :+1: to give.

We have already patched this out of the sunpy fork iirc.

**Comment by bsipocz** [comment]
sounds good to me

**Comment by astrofrog** [comment]
Anyone want to do a quick PR for this? :)

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
