### ISSUE TITLE
Python version check comes to late (for version 2 at least)

### ISSUE THREAD

**Issue by mhvk** [astropy/package-template#428]
In `__init__.py`, the check on the python version comes after importing `_astropy_init`, which means that if one tries to import under python2, a bug is raised before the version check happens.

I think the order can be safely swapped (or, perhaps better, the version check can happen inside `_astropy_init.py`)

Also, ideally, of course there is only one place where the minimum version is defined...

p.s. EDIT: in my packages, I have simply removed the version check; things either work or they don't...

**Comment by Cadair** [comment]
> Also, ideally, of course there is only one place where the minimum version is defined...

This turned out to be practically impossible, which is why we ended up with it twice fwiw.

**Comment by pllim** [comment]
Is this still an issue?

**Comment by astrofrog** [comment]
Technically it's still an issue, although people shouldn't really run into it if they define ``python_requires`` properly, which this template does. In any case I think the real fix is what @mhvk mentioned - we should just remove this check from ``__init__.py``. Should be an easy PR if anyone wants to give it a go :) (I'll happily approve).
