### ISSUE TITLE
Sphinx automodapi broken?

### ISSUE THREAD

**Issue by bmorris3** [astropy/package-template#430]
I just recently created [a package](https://github.com/bmorris3/kelp) using the package template and tried to run `python setup.py build_docs`, and also tried building docs on RTD, and in both cases automodapi does not build the API documentation, it just generates a [blank page](https://kelp.readthedocs.io/en/latest/kelp/index.html#reference-api). Am I doing something wrong, or is something wrong with the package template, or might there be a problem with automodapi?

Thanks!

**Comment by bmorris3** [comment]
Here's a build where the batman fix is implemented, but `automodapi` doesn't seem to kick in: 

https://readthedocs.org/projects/kelp/builds/9659655/

**Comment by pllim** [comment]
Are you sure you ask RTD to install `automodapi`? I don't see any trace of it being installed in your log. https://readthedocs.org/api/v2/build/9659655.txt

**Comment by pllim** [comment]
So, I guess, either there is a misconfiguration in your RTD admin settings, or whatever in the template is not playing well with RTD anymore... :thinking:

**Comment by bmorris3** [comment]
I think I've found the problem. [This line](https://github.com/astropy/package-template/blob/cookiecutter/%7B%7B%20cookiecutter.package_name%20%7D%7D/%7B%7B%20cookiecutter.module_name%20%7D%7D/__init__.py#L16) seems to squelch any imported classes/functions in the lines that follow it. By removing the `__all__ = []` line, I get successful docs builds...

**Comment by bmorris3** [comment]
Upon looking at the latest version of the package-template, I think this bug is resolved in some recent commits, so I'm going to close this error, but not before leaving a little note to future Issue searchers: if you're running into bugs with an older version of the package-template, be mindful of the `__all__` floating around in the repo/package/__init__.py file!
