### ISSUE TITLE
MNT: Use ReadTheDocs v2 YAML and not conda

### ISSUE THREAD

**Issue by pllim** [astropy/package-template#431]
1. Upgrade from v1 to v2 ReadTheDocs YAML specifications. See https://docs.readthedocs.io/en/stable/config-file/v2.html
2. Stop using `conda` to set up the environment. Use `pip` all around for faster build time and more predictable outcome.

**Comment by pllim** [comment]
p.s. I can take a stab at this if you want, but I want to make sure everyone is on board first.

**Comment by bsipocz** [comment]
Sounds like a good plan to me. We need to do point no1 anyway, and the no2 sounds quite reasonable to me, too.

**Comment by pllim** [comment]
Fixed in #438
