### ISSUE TITLE
Setting up coveralls not obvious

### ISSUE THREAD

**Issue by mhvk** [astropy/package-template#444]
Probably I'm just missing things, but astropy's `.travis.yml` has more lines about coverage than the template here; in particular,
```
    - if [[ $TOXENV == *-cov ]]; then
        export TOXPOSARGS=$TOXPOSARGS" --cov-report=xml:"$TRAVIS_BUILD_DIR"/coverage.xml";
      fi
```
Is this important?

Also, we use what seems a new package, `codecov` - does this still push to `coveralls.io`? Would be good to update "next steps" to be clear about it (which I'm happy to do, but I need to be clear about it first!).

**Comment by mhvk** [comment]
I guess issue #368 partially answers this - but even more reason to update the docs!

**Comment by bsipocz** [comment]
Yes, I suppose we've switched to codecov everywhere now, but updating the docs might have lost in the weeds.

**Comment by mhvk** [comment]
Any idea what those extra lines do? (Added by @saimn, so pinging...)

**Comment by bsipocz** [comment]
No, I'm not exactly sure why that env variable needs to be exported as oppose to the other jobs. Arguably @saimn's changes were originated from https://github.com/astropy/astropy/pull/8248/files, but even there I see no trace of mentioning the xml, neither the export of the variable. Maybe @astrofrog can shed light on the question?

**Comment by mhvk** [comment]
Also, does anyone know how to get rid of the `coveralls` in the checks for a PR? (I promise I'll make a PR for the template docs!)

**Comment by bsipocz** [comment]
I think it should be listed as a `webhook` in the settings menu of the project's repo. Delete the webhook and it should be fine (along with the changes in the travis config, etc, along the ones made in e.g. https://github.com/astropy/astropy/pull/7879)

**Comment by bsipocz** [comment]
(if it's not there, pls let me know, it was just a guess, as I don't think I have access to any settings any more that still uses coveralls).

**Comment by pllim** [comment]
Either webhook or app, I can't remember now, but I do remember it is on the admin panel.

**Comment by mhvk** [comment]
Thanks for the tips - it turned out I also needed to remove coveralls in "branches", in the protection of the master branch.

**Comment by pllim** [comment]
I think we use codecov now? Is this still relevant?

**Comment by mhvk** [comment]
No, I don't think so, so closing.
