### ISSUE TITLE
tox displays plot during testing

### ISSUE THREAD

**Issue by bmorris3** [astropy/package-template#450]
I'm using the package template [over here](https://github.com/bmorris3/eugene) and running into a small problem when running `tox -e test` locally. When tox gets to the step: 
```
test run-test: commands[1] | pytest --pyargs eugene /Users/brettmorris/git/eugene/docs
```
(i.e. test the docs), it actually displays one of the plots to the screen generated by [the plot directive in the documentation](https://github.com/bmorris3/eugene/blob/master/docs/eugene/gettingstarted.rst). How can we suppress plots from being displayed to screen during local testing? Thanks!

**Comment by bmorris3** [comment]
Upon further investigation it wasn't the plot directive, it was the code-block that executed the plot that was causing the problem. If I add 
```
...
[testenv]
setenv = MPLBACKEND=agg
...
```
to my `tox.ini` I can run the tests locally without getting a plot.

**Comment by astrofrog** [comment]
That is indeed the best way to solve that issue. Should we include it by default in the template?

**Comment by bmorris3** [comment]
My vote is yes! See #453.
