### ISSUE TITLE
Default template settings don't pass initial test

### ISSUE THREAD

**Issue by bmorris3** [astropy/package-template#456]
I'm currently working with the latest version of the package-template to build a new package, and I'm unexpected getting test failures both locally and on Travis [when I try to run the tests](https://travis-ci.com/github/bmorris3/retrieval/jobs/302542519#L313). Anyone know where I need to insert astropy to fix tox? Thanks!

**Comment by Cadair** [comment]
This template should probably be rebased off / merge in the openastronomy one as I have implemented proper tests for the template which would catch this there.

@bmorris3 I would think you need to add it in `install_requires` in the `setup.cfg` file.

**Comment by bmorris3** [comment]
That fixed it, thanks @Cadair! Sorry I couldn't get there myself 😄

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
