### ISSUE TITLE
APE17 - cookiecutter fails step 0 - example setup.py?

### ISSUE THREAD

**Issue by HeloiseS** [astropy/package-template#463]
Hello,

trying to do the migration in APE17: https://docs.astropy.org/projects/package-template/en/latest/ape17.html#step-rerender

Step 0 fails - badly for me - I checked if i could do this import in my interpreter and I have no issue so i don't know what's gone wrong
```
Traceback (most recent call last):
  File "/tmp/tmpnubQPB.py", line 5, in <module>
    import urllib.request
ImportError: No module named request
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
```

Anyways, since i don't have my new shiny setup.py is it fine to use the astropy one as a basis?

**Comment by Cadair** [comment]
This looks like a real bug in the template, the names of the files in the template and the hook don't match. Easiest immediate workaround for you @HeloiseS is to just set `use_readthedocs` to true and delete the files yourself.

**Comment by HeloiseS** [comment]
Thanks :) will do

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
