### ISSUE TITLE
How to set the version with the latest package template

### ISSUE THREAD

**Issue by bmorris3** [astropy/package-template#474]
Currently the [`setup.cfg`](https://github.com/astropy/package-template/blob/cookiecutter/%7B%7B%20cookiecutter.package_name%20%7D%7D/setup.cfg#L13) file doesn't contain a `version` keyword, but the [astropy package-template docs page](https://docs.astropy.org/en/latest/development/astropy-package-template.html) asks you explicitly to edit the `version` of the software in the `setup.cfg` file. I've tried adding a version keyword to the setup.cfg file but that seems not to get used. How should the version of the software be set?

**Comment by bmorris3** [comment]
@cadair answered this question with a [reference to the docs](https://packaging-guide.openastronomy.org/en/latest/releasing.html#incrementing-version-numbers) via Slack. Perhaps we need to update the astropy docs to match?

**Comment by pllim** [comment]
I think the text in Steps 9 and 10 in astropy dev doc was an oversight. Thanks for catching that. Please open a pull request. Thank you!
