### ISSUE TITLE
Create .git folder on render

### ISSUE THREAD

**Issue by nstarman** [astropy/package-template#479]
it would be nice to be able to import a repository into GitHub rather than create the repo and add the cookiecutter-generated contents.
I think adding a .git folder with the bare minimum of files could accomplish this.

<img width="561" alt="Screen Shot 2020-09-10 at 15 59 21" src="https://user-images.githubusercontent.com/8949649/92795734-9afe3000-f37e-11ea-8bb7-fcf2ba8ccf27.png">

**Comment by Cadair** [comment]
We used to do this, but it was a bit of a pain. All you need to do is run `git init` after cookiecutter.

**Comment by nstarman** [comment]
Fair enough. I'm just looking at the large number of items I still do on project startup and hoping to automate them away. 
What specifically was the pain point?
Could a post_gen_project hook make the folder afterwards? Or is `git init` preferable?

![Screen Shot 2020-09-26 at 17 09 43](https://user-images.githubusercontent.com/8949649/94350317-216f6e80-001b-11eb-850d-34e7c02f9c55.png)

**Comment by mwcraig** [comment]
This is an interesting idea but I'm a little hesitant to impose the requirement that a .git folder be created. I could see that leading, in some edge cases, to unexpected behavior. 

It might work as an option in the cookiecutter dialog to create a git repo by running `git init` post-generation, though I 'd argue for a default value of "no" for the option.

**Comment by Cadair** [comment]
[here](https://github.com/astropy/package-template/blob/34c5256e192113882fa52ccbb30a15cd002f3b6a/hooks/post_gen_project.py#L61) is an old version of the hook which used gitpython to init the repo and the old astropy_helpers submodule.

**Comment by nstarman** [comment]
Thanks for the suggestions. I like the idea of actually running `git init` rather than manually generating the file.

**Comment by Cadair** [comment]
yeah I wouldn't recommend manually generating it.

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
