### ISSUE TITLE
Make rendered branch a GitHub template

### ISSUE THREAD

**Issue by nstarman** [astropy/package-template#480]
I'm not sure if there are technical details preventing this, but it would be great if the rendered branch (currently `master`) was a GitHub template and showed up as an option in the dropdown menu when creating a new repository.

<img width="582" alt="Screen Shot 2020-09-10 at 16 01 41" src="https://user-images.githubusercontent.com/8949649/92796148-f03a4180-f37e-11ea-8366-ca880eac583f.png">

**Comment by pllim** [comment]
GitHub repo template didn't exist when we created this. There is no current plan to migrate to use GitHub template.

**Comment by nstarman** [comment]
Makes sense. The current implementation of GitHub templates is pretty limited, but it looks like it might just be one click ( https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/ ). I don't know if it can be limited to the rendered branch, leaving the cookiecutter main branch unchanged.

**Comment by pllim** [comment]
@Cadair is the `cookiecutter` expert here, so perhaps he can comment. 🤞

**Comment by nstarman** [comment]
Also, something that was mentioned in #421 — if this is possible, then adding a GitHub action to render and push to master from the cookiecutter branch would allow anyone forking the repository to add that action to their repository. Any forked repositories would then also have GitHub template that reflect changes in the cookiecutter branch.

**Comment by pllim** [comment]
Re: https://github.com/astropy/package-template/issues/480#issuecomment-690744704 -- Sounds interesting!

**Comment by nstarman** [comment]
Unfortunately I cannot do a PR for GH actions. I'll try to get something working on my fork and then share the yaml file.

**Comment by embray** [comment]
The existence of GitHub [project templates](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) is an entirely new discovery to me, so I'm not sure what this would entail.  Sounds like a good idea though!

**Comment by embray** [comment]
> Also, something that was mentioned in #421 — if this is possible, then adding a GitHub action to render and push to master from the cookiecutter branch would allow anyone forking the repository to add that action to their repository. Any repository fork would then also have a GitHub template that reflects changes in the cookiecutter branch.

That would work if they fork the repository, but what if they create it from a template, or from scratch? 

Regardless, we could still come up with a mechanism (not necessarily reliant on forking) to use Actions to easily apply updates (or at least attempt to) from the package template.  This should be done at the package owner's discretion though, not necessarily automatically.

**Comment by embray** [comment]
I see now that when creating a repository from a template it is possible to choose all branches from the template as well.

**Comment by nstarman** [comment]
> I see now that when creating a repository from a template it is possible to choose all branches from the template as well.

Good to know. I was dreading the conversation about making `main` (master)  the default branch.

**Comment by embray** [comment]
I see now that the feature is rather simple.  I thought it might incorporate some cookie-cutter-like functionality, but it literally just copies the repository without explicitly forking or copying the history.  So I think it makes total sense to just go ahead and do this.  The Action niceties could come later, though it might not be too hard to add either (I have not worked with GitHub Actions yet other than a couple code reviews of other peoples' action implementations).

**Comment by nstarman** [comment]
As making this repo a GitHub template is just a button in settings, maybe this Issue should be tagged with `keep-open` for the Action implementation.

**Comment by pllim** [comment]
FWIW, I made https://github.com/spacetelescope/stsci-package-template into a static GitHub repo template. Maybe simple is good. You start with the barest possible skeleton as a package and then add stuff to it as needed, rather than starting off with all the bells and whistles and then trying to figure out which parts you don't really need. But YMMV.

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
