### ISSUE TITLE
Don't docstest `extern` contents

### ISSUE THREAD

**Issue by nstarman** [astropy/package-template#486]
The extern module contains bundled codes. As the default, doctstring-plus tests may/should not be applied ?

I have a branch open with this small change. Should I PR?

in tox.ini

```
[tool:pytest]
doctest_norecursedirs=*/{{ cookiecutter.module_name }}/extern/*
```

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
