### ISSUE TITLE
Add pre-commit for isort & flake8

### ISSUE THREAD

**Issue by nstarman** [astropy/package-template#490]
I use pre-commit with isort & flake8 (and other code stylers, but those are the important ones). Having this on render is nice, particularly since Travis has a flake8 test.

Only one file is added — pre-commit-config.yaml. The isort and flake8 configurations are kept in pyproject.toml and setup.cfg

This could be opt-in/out or just packaged.

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
