### ISSUE TITLE
Interest for a series of PRs

### ISSUE THREAD

**Issue by nstarman** [astropy/package-template#491]
Trying to merge code I have in my repo fork.

1. [Add credits.rst file](https://github.com/astropy/package-template/compare/cookiecutter...nstarman:add-credits-on-render) to rendered docs [#492]
2. [Add installation instructions](https://github.com/astropy/package-template/compare/cookiecutter...nstarman:installation-docs) to rendered docs [#493]
3. [Add pre-commit](https://github.com/astropy/package-template/compare/cookiecutter...nstarman:pre-commit) [#490] for isort and flake8. I'd remove the black code-styler.
4. [Don't doctest extern contents](https://github.com/astropy/package-template/compare/cookiecutter...nstarman:no-doctest-extern) [#486] 
5. [flake8 configuration](https://github.com/astropy/package-template/compare/cookiecutter...nstarman:flake8-config)
6. allow-fail [unused code static analyzer](https://github.com/astropy/package-template/compare/cookiecutter...nstarman:unused-code-static-analyzer)
7. [basic mypy configuration](https://github.com/astropy/package-template/compare/cookiecutter...nstarman:travis-check-mypy)

**Comment by pllim** [comment]
Thanks for your interest and sorry it didn't work out over here!
