### ISSUE TITLE
Do not ship commented out config for CI

### ISSUE THREAD

**Issue by bsipocz** [astropy/package-template#504]
Many years of experience shows that commented out CI config is the wrong approach to ship this template. I strongly suggest to either make them opt in at cookicutter time, or just simply have them enabled in the matrix. The current approach doesn't answer to the question of why those are commented out, what their purpose is and what extra they bring if they are not commented out.

https://github.com/astropy/package-template/blob/cookiecutter/%7B%7B%20cookiecutter.package_name%20%7D%7D/.github/workflows/ci_tests.yml#L50

**Comment by pllim** [comment]
@tepickering , do you remember why they were commented out?

**Comment by tepickering** [comment]
iirc, there was a complaint that the default matrix was too large. so i commented them out to leave as ready-to-implement examples if users wanted to cover those cases. they're less-commonly used edge-ish cases so probably best to remove them. is there documentation somewhere on the use of github actions w/in the astropy ecosystem and recommended best practices? if it exists, that could be pointed to for guidance and examples...

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
