### ISSUE TITLE
`package_data` in APE 17 migration guide

### ISSUE THREAD

**Issue by epassaro** [astropy/package-template#513]
Followed the [migration guide](https://docs.astropy.org/projects/package-template/en/latest/ape17.html) and the `package_data` was not included.

I needed to add `include_package_data = True` under `[options]`.

Then, it worked.

**Comment by pllim** [comment]
But it is in the template:

https://github.com/astropy/package-template/blob/bf8ce319e8ec99c38ab80c8af8c0437c16de0474/%7B%7B%20cookiecutter.package_name%20%7D%7D/setup.cfg#L42-L43

**Comment by astrofrog** [comment]
The include_package_data option actually bypasses the package_data option and uses the manifest instead so you should either use include_package_data or package_data but not both. If the latter doesn't work, there might be a syntax or path issue in it. Could you post a link to your setup.cfg file?

**Comment by epassaro** [comment]
This is the working `setup.cfg`: https://github.com/epassaro/tardis/blob/ape-17-migration/setup.cfg

This is my `MANIFEST.in` that does not include all those extensions :thinking: https://github.com/epassaro/tardis/blob/ape-17-migration/MANIFEST.in

**Comment by epassaro** [comment]
Please ignore this issue. Closing.
