### ISSUE TITLE
Switch to the `src/` based layout?

### ISSUE THREAD

**Issue by maxnoe** [astropy/package-template#522]
There is a wide range of opinions on this, but I now more and more came to the conclusion that there are only upsides and basically no downsides to having the main python package not in the root of the directory but in a `src/` subdirectory.

The current python packaging guide recommends this layout here:
https://packaging.python.org/en/latest/tutorials/packaging-projects/ 
and in their sample package here: https://github.com/pypa/sampleproject

A list of reasons can be found here (2014 / update in 2019):
* https://blog.ionelmc.ro/2014/05/25/python-packaging/

Note:  Opposed to this guide's recommendation, I prefer tests in tree, so users can run the tests for the installed package.

**Comment by nstarman** [comment]
Any interest in jointly proposing this for astropy as well? It's something I've been considering.

**Comment by maxnoe** [comment]
@astrofrog No downsides for new projects, changing this for astropy would probably be a huge pain in the ...

**Comment by saimn** [comment]
> @astrofrog No downsides for new projects, changing this for astropy would probably be a huge pain in the ...

I'm not sure if it would be painful to do but at least switching to a `src` layout should allow to test the installed package without having to import astropy in pytest-astropy-header :thinking:  : https://github.com/astropy/pytest-astropy-header/issues/41

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
