### ISSUE TITLE
Autoclosing issue in package-template closes issue in affiliated package

### ISSUE THREAD

**Issue by bsipocz** [astropy/package-template#81]
It seems like using the "autofix / close issue" feature in `package-template` closes the matching issues in packages where the template was used. I'm not sure this is considered to be a bug or just an antifeature of github.

Example:
https://github.com/astropy/photutils/issues/69#event-130488245

**Comment by bsipocz** [comment]
Another similar issue is that package template tags are being inherited in packages and are soo damn difficult to clean up years after the fact (e.g. we have `1.0` etc in astroquery, that are coming back each time I fetch from someone else's fork). 

For the issues, we can indeed deal with it with using the `astropy/package-template###`, as suggested above.  Also, I believe it becomes less of an issue since we switched to cookiecutter rather than suggesting to bring the repo history.

So overall, I suggest to close this, as there isn't much we can do here (we could rewrite the commit messages and force push, a tiny bit drastic, but that's the only thing we could do about the past).

**Comment by pllim** [comment]
This issue will still be pinned even after close.
